# Generated by Django 3.2.8 on 2021-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='image'),
        ),
    ]
