# Generated by Django 3.2.8 on 2021-10-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0005_alter_produit_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
    ]
