# Generated by Django 3.2.8 on 2021-10-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0006_remove_produit_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
